language: php
php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2

before_install:
    # turn off XDebug
    - phpenv config-rm xdebug.ini || return 0

    # Create databases.neon
    - cp ./tests/config/config.travis.neon ./tests/config/config.local.neon

    # Create Postgre database
    - psql -c "CREATE DATABASE salamium_test WITH ENCODING 'UTF8' LC_COLLATE='POSIX' TEMPLATE=template0" -U postgres

    # Create Mysql database
    - cat tests/config/schema.sql | mysql -u root

    # enable coverage
    - if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then NTESTER_FLAGS="phpdbg --coverage ./coverage.xml --coverage-src ./src"; else NTESTER_FLAGS=""; fi

install:
    - travis_retry composer install --no-progress --prefer-dist

script:
    - ./tests/run-tests $NTESTER_FLAGS

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

    # send coverage xml
    - if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then
      wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
      && php coveralls.phar --verbose --config tests/.coveralls.yml
      || true;
      fi

sudo: false

cache:
    directories:
        - $HOME/.composer/cache