language: php
php:
  - 5.6
  - 7.0
  - 7.1

matrix:
    include:
        - php: 7.1
          env: coverage=on

before_script:
  - composer self-update
  -
  - if [ "$coverage" == "on" ]; then NTESTER_FLAGS="phpdbg --coverage ./coverage.xml --coverage-src ./src"; else NTESTER_FLAGS=""; fi
  - psql -c "CREATE DATABASE salamium_test WITH ENCODING 'UTF8' LC_COLLATE='POSIX' TEMPLATE=template0" -U postgres

after_script:
    - if [ "$coverage" == "on" ]; then
      wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
      && php coveralls.phar --verbose --config tests/.coveralls.yml
      || true;
      fi

script:
  - ./tests/run-tests $NTESTER_FLAGS

