#!/bin/bash

DIR=`pwd`/`dirname $0`;

cd $DIR/..
composer install
cd -

if [ $# -eq 0 ]; then
    args="-p php $DIR/src"
else
    args=$@
fi

$DIR/../vendor/bin/tester -l $DIR/temp/test.log -s -j 5 --colors 1 -c $DIR/config/php.ini $args